version: '2'
services:
    tomcat-node-1:
      image: tomcat:7
      container_name: tomcat-node-1
      ports:
        - 8081:8080
      volumes:
        - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
        - ./tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
        - ./target/session-replication.war:/usr/local/tomcat/webapps/session-replication.war

    tomcat-node-2:
      image: tomcat:7
      container_name: tomcat-node-2
      ports:
        - 8082:8080
      volumes:
        - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
        - ./tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
        - ./target/session-replication.war:/usr/local/tomcat/webapps/session-replication.war
